---
title: "Covid case study"
author: ""
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(purrr)
library(rstan)
library(bayesplot)
library(ggplot2)
library(mvtnorm)
library(parallel)
library(usethis)
library(reshape2)
library(ggplot2)
library(gridExtra)
library(grid)
```

Creat observational data for Covid model:

```{r}
set.seed(5)
D = 60
```


```{r}
set.seed(5)
mu_U_SARS_Ang = 45
sigma_U_SARS_Ang = 10
U_SARS_Ang <- rnorm(500, mu_U_SARS_Ang, sigma_U_SARS_Ang)

beta0_U_SARS_AngToSARS_COV2 = -2
beta_U_SARS_AngToSARS_COV2 = 0.05 #positive
SARS_COV2 = 100 / (1 + exp(-beta0_U_SARS_AngToSARS_COV2 -U_SARS_Ang * beta_U_SARS_AngToSARS_COV2))

beta0_SARS_COV2ToACE2 = 20
beta_SARS_COV2ToACE2 = -0.1 #negative
ACE2 = beta0_SARS_COV2ToACE2 + SARS_COV2 * beta_SARS_COV2ToACE2

beta0_ACE2_and_U_SARS_Ang_ToAng = 25
beta_ACE2ToAng = -0.8 #negative
beta_U_SARS_AngToAng = 0.5 #positive
Ang = beta0_ACE2_and_U_SARS_Ang_ToAng + ACE2 * beta_ACE2ToAng + U_SARS_Ang *beta_U_SARS_AngToAng

beta0_AngToAGTR1 = -1.5
beta_AngToAGTR1 = 0.08
AGTR1 = 100 / (1 + exp(-beta0_AngToAGTR1 - Ang * beta_AngToAGTR1))

mu_U_ADAM17_Sil6r = 50
sigma_U_ADAM17_Sil6r= 10
U_ADAM17_Sil6r <- rnorm(500, mu_U_ADAM17_Sil6r, sigma_U_ADAM17_Sil6r)

beta0_AGTR1_UToADAM17 = -3.8
beta_AGTR1ToADAM17 = 0.04
beta_U_ADAM17_Sil6rToADAM17 = 0.04
ADAM17 = 100 / (1 + exp(-beta0_AGTR1_UToADAM17 - AGTR1 * beta_AGTR1ToADAM17 - U_ADAM17_Sil6r * beta_U_ADAM17_Sil6rToADAM17))

mu_Toci = 45
sigma_Toci = 10
Toci <- rnorm(500, mu_Toci, sigma_Toci)

beta0_ADAM17_U_TociToSil6r = -3
beta_ADAM17ToSil6r = 0.03
beta_UToSil6r = 0.05
beta_TociToSil6r = -0.04 #negative
Sil6r = 100 / (1 + exp(-beta0_ADAM17_U_TociToSil6r - ADAM17 * beta_ADAM17ToSil6r - U_ADAM17_Sil6r * beta_UToSil6r - Toci * beta_TociToSil6r))


mu_U_EGF_EGFR = 50
sigma_U_EGF_EGFR = 10
U_EGF_EGFR = rnorm(500, mu_U_EGF_EGFR, sigma_U_EGF_EGFR)

beta0_ADAM17_UToEGF = -3
beta_ADAM17ToEGF = 0.03
beta_UToEGF = 0.05
EGF = 100 / (1 + exp(-beta0_ADAM17_UToEGF - ADAM17 * beta_ADAM17ToEGF - U_EGF_EGFR * beta_UToEGF))

mu_U_EGFR_TNF = 45
sigma_U_EGFR_TNF = 10
U_EGFR_TNF = rnorm(500, mu_U_EGFR_TNF, sigma_U_EGFR_TNF)

beta0_ADAM17_UToTNF = -4.1
beta_ADAM17ToTNF = 0.05
beta_UToTNF = 0.06
TNF = 100 / (1 + exp(-beta0_ADAM17_UToTNF - ADAM17 * beta_ADAM17ToTNF - U_EGFR_TNF * beta_UToTNF))

mu_U_EGFR_IL6STAT3 = 40
sigma_U_EGFR_IL6STAT3 = 10
U_EGFR_IL6STAT3 <- rnorm(500, mu_U_EGFR_IL6STAT3, sigma_U_EGFR_IL6STAT3)

beta0_EGF_3U = -6
beta_EGFToEGFR = 0.03
beta_U1ToEGFR = 0.05
beta_U2ToEGFR = 0.02
beta_U3ToEGFR = 0.04
EGFR = 100 / (1 + exp(-beta0_EGF_3U - EGF * beta_EGFToEGFR - U_EGFR_IL6STAT3 * beta_U1ToEGFR - U_EGFR_TNF * beta_U2ToEGFR  - U_EGF_EGFR * beta_U3ToEGFR))

mu_U_PRR_NFKB = 40
sigma_U_PRR_NFKB = 10
U_PRR_NFKB <- rnorm(500, mu_U_PRR_NFKB, sigma_U_PRR_NFKB)

beta0_SARS_UPRR = -3.4
beta_SARS_COV2ToPRR = 0.05
beta_UToPRR = 0.02
PRR = 100 / (1 + exp(-beta0_SARS_UPRR - SARS_COV2 * beta_SARS_COV2ToPRR - U_PRR_NFKB * beta_UToPRR))

beta0_PRR_U_EGFR_TNFToNFKB = -5
beta_PRRToNFKB = 0.01
beta_UToNFKB = 0.02
beta_EGFRToNFKB = 0.02
beta_TNFToNFKB = 0.03
NFKB = 100 / (1 + exp(-beta0_PRR_U_EGFR_TNFToNFKB - PRR * beta_PRRToNFKB - U_PRR_NFKB * beta_UToNFKB - EGFR * beta_EGFRToNFKB  - TNF * beta_TNFToNFKB))

beta0_NFKB_IL6STSTToIL6STAT3 = -4.6
beta_UToIL6STAT3 = 0.05
beta_Sil6rToIL6STAT3 = 0.04
IL6STAT3 = 100 / (1 + exp(-beta0_NFKB_IL6STSTToIL6STAT3 - U_EGFR_IL6STAT3 * beta_UToIL6STAT3 - Sil6r * beta_Sil6rToIL6STAT3))

beta0_NFKB_IL6STATToIL6AMP = -3.7
beta_NFKBToIL6AMP = 0.02
beta_IL6STAT3ToIL6AMP = 0.03
IL6AMP = 100 / (1 + exp(-beta0_NFKB_IL6STATToIL6AMP - NFKB * beta_NFKBToIL6AMP - IL6STAT3 * beta_IL6STAT3ToIL6AMP))

beta0_IL6AMPTocytok = -2
beta_IL6AMPTocytok = 0.06
cytok = 100 / (1 + exp(-beta0_IL6AMPTocytok - IL6AMP * beta_IL6AMPTocytok))

observational_data <- data.frame("U_SARS_Ang" = U_SARS_Ang
                  ,"SARS_COV2" = SARS_COV2
                  ,"ACE2" = ACE2
                  ,"Ang" = Ang
                  ,"AGTR1" = AGTR1
                  ,"U_ADAM17_Sil6r" = U_ADAM17_Sil6r
                  ,"ADAM17" = ADAM17
                  ,"Toci" = Toci
                  ,"Sil6r" = Sil6r
                  ,"U_EGF_EGFR" = U_EGF_EGFR
                  ,"EGF" = EGF
                  ,"U_EGFR_TNF" = U_EGFR_TNF
                  ,"TNF" = TNF
                  ,"U_EGFR_IL6STAT3" = U_EGFR_IL6STAT3
                  ,"EGFR" = EGFR
                  ,"U_PRR_NFKB" = U_PRR_NFKB
                  ,"PRR" = PRR
                  ,"NFKB" = NFKB
                  ,"IL6STAT3" = IL6STAT3
                  ,"IL6AMP" = IL6AMP
                  ,"cytok" = cytok)
```

Creat interventional data for Covid model:

```{r}
set.seed(5)
mu_U_SARS_Ang = 45
sigma_U_SARS_Ang = 10
U_SARS_Ang <- rnorm(500, mu_U_SARS_Ang, sigma_U_SARS_Ang)

beta0_U_SARS_AngToSARS_COV2 = -2
beta_U_SARS_AngToSARS_COV2 = 0.05 #positive
SARS_COV2 = 100 / (1 + exp(-beta0_U_SARS_AngToSARS_COV2 -U_SARS_Ang * beta_U_SARS_AngToSARS_COV2))

beta0_SARS_COV2ToACE2 = 20
beta_SARS_COV2ToACE2 = -0.1 #negative
ACE2 = beta0_SARS_COV2ToACE2 + SARS_COV2 * beta_SARS_COV2ToACE2

beta0_ACE2_and_U_SARS_Ang_ToAng = 25
beta_ACE2ToAng = -0.8 #negative
beta_U_SARS_AngToAng = 0.5 #positive
Ang = beta0_ACE2_and_U_SARS_Ang_ToAng + ACE2 * beta_ACE2ToAng + U_SARS_Ang *beta_U_SARS_AngToAng

beta0_AngToAGTR1 = -1.5
beta_AngToAGTR1 = 0.08
AGTR1 = 100 / (1 + exp(-beta0_AngToAGTR1 - Ang * beta_AngToAGTR1))

mu_U_ADAM17_Sil6r = 50
sigma_U_ADAM17_Sil6r= 10
U_ADAM17_Sil6r <- rnorm(500, mu_U_ADAM17_Sil6r, sigma_U_ADAM17_Sil6r)

beta0_AGTR1_UToADAM17 = -3.8
beta_AGTR1ToADAM17 = 0.04
beta_U_ADAM17_Sil6rToADAM17 = 0.04
ADAM17 = 100 / (1 + exp(-beta0_AGTR1_UToADAM17 - AGTR1 * beta_AGTR1ToADAM17 - U_ADAM17_Sil6r * beta_U_ADAM17_Sil6rToADAM17))

mu_Toci = 45
sigma_Toci = 10
Toci <- rnorm(500, mu_Toci, sigma_Toci)


Sil6r = 20


mu_U_EGF_EGFR = 50
sigma_U_EGF_EGFR = 10
U_EGF_EGFR = rnorm(500, mu_U_EGF_EGFR, sigma_U_EGF_EGFR)

beta0_ADAM17_UToEGF = -3
beta_ADAM17ToEGF = 0.03
beta_UToEGF = 0.05
EGF = 100 / (1 + exp(-beta0_ADAM17_UToEGF - ADAM17 * beta_ADAM17ToEGF - U_EGF_EGFR * beta_UToEGF))

mu_U_EGFR_TNF = 45
sigma_U_EGFR_TNF = 10
U_EGFR_TNF = rnorm(500, mu_U_EGFR_TNF, sigma_U_EGFR_TNF)

beta0_ADAM17_UToTNF = -4.1
beta_ADAM17ToTNF = 0.05
beta_UToTNF = 0.06
TNF = 100 / (1 + exp(-beta0_ADAM17_UToTNF - ADAM17 * beta_ADAM17ToTNF - U_EGFR_TNF * beta_UToTNF))

mu_U_EGFR_IL6STAT3 = 40
sigma_U_EGFR_IL6STAT3 = 10
U_EGFR_IL6STAT3 <- rnorm(500, mu_U_EGFR_IL6STAT3, sigma_U_EGFR_IL6STAT3)

beta0_EGF_3U = -6
beta_EGFToEGFR = 0.03
beta_U1ToEGFR = 0.05
beta_U2ToEGFR = 0.02
beta_U3ToEGFR = 0.04
EGFR = 100 / (1 + exp(-beta0_EGF_3U - EGF * beta_EGFToEGFR - U_EGFR_IL6STAT3 * beta_U1ToEGFR - U_EGFR_TNF * beta_U2ToEGFR  - U_EGF_EGFR * beta_U3ToEGFR))

mu_U_PRR_NFKB = 40
sigma_U_PRR_NFKB = 10
U_PRR_NFKB <- rnorm(500, mu_U_PRR_NFKB, sigma_U_PRR_NFKB)

beta0_SARS_UPRR = -3.4
beta_SARS_COV2ToPRR = 0.05
beta_UToPRR = 0.02
PRR = 100 / (1 + exp(-beta0_SARS_UPRR - SARS_COV2 * beta_SARS_COV2ToPRR - U_PRR_NFKB * beta_UToPRR))

beta0_PRR_U_EGFR_TNFToNFKB = -5
beta_PRRToNFKB = 0.01
beta_UToNFKB = 0.02
beta_EGFRToNFKB = 0.02
beta_TNFToNFKB = 0.03
NFKB = 100 / (1 + exp(-beta0_PRR_U_EGFR_TNFToNFKB - PRR * beta_PRRToNFKB - U_PRR_NFKB * beta_UToNFKB - EGFR * beta_EGFRToNFKB  - TNF * beta_TNFToNFKB))

beta0_NFKB_IL6STSTToIL6STAT3 = -4.6
beta_UToIL6STAT3 = 0.05
beta_Sil6rToIL6STAT3 = 0.04
IL6STAT3 = 100 / (1 + exp(-beta0_NFKB_IL6STSTToIL6STAT3 - U_EGFR_IL6STAT3 * beta_UToIL6STAT3 - Sil6r * beta_Sil6rToIL6STAT3))

beta0_NFKB_IL6STATToIL6AMP = -3.7
beta_NFKBToIL6AMP = 0.02
beta_IL6STAT3ToIL6AMP = 0.03
IL6AMP = 100 / (1 + exp(-beta0_NFKB_IL6STATToIL6AMP - NFKB * beta_NFKBToIL6AMP - IL6STAT3 * beta_IL6STAT3ToIL6AMP))

beta0_IL6AMPTocytok = -2
beta_IL6AMPTocytok = 0.06
cytok = 100 / (1 + exp(-beta0_IL6AMPTocytok - IL6AMP * beta_IL6AMPTocytok))

interventional_data <- data.frame("U_SARS_Ang" = U_SARS_Ang
                                  ,"SARS_COV2" = SARS_COV2
                                  ,"ACE2" = ACE2
                                  ,"Ang" = Ang
                                  ,"AGTR1" = AGTR1
                                  ,"U_ADAM17_Sil6r" = U_ADAM17_Sil6r
                                  ,"ADAM17" = ADAM17
                                  ,"Toci" = Toci
                                  ,"Sil6r" = 25
                                  ,"U_EGF_EGFR" = U_EGF_EGFR
                                  ,"EGF" = EGF
                                  ,"U_EGFR_TNF" = U_EGFR_TNF
                                  ,"TNF" = TNF
                                  ,"U_EGFR_IL6STAT3" = U_EGFR_IL6STAT3
                                  ,"EGFR" = EGFR
                                  ,"U_PRR_NFKB" = U_PRR_NFKB
                                  ,"PRR" = PRR
                                  ,"NFKB" = NFKB
                                  ,"IL6STAT3" = IL6STAT3
                                  ,"IL6AMP" = IL6AMP
                                  ,"cytok" = cytok)
#interventional_data$cytok
#54 parameters in total
```


```{r}
model_str_covid <- "
    data {
        int D;
        vector[D] SARS_COV2;
        vector[D] ACE2;
        vector[D] Ang;
        vector[D] AGTR1;
        vector[D] ADAM17;
        vector[D] Toci;
        vector[D] Sil6r;
        vector[D] EGF;
        vector[D] TNF;
        vector[D] EGFR;
        vector[D] PRR;
        vector[D] NFKB;
        vector[D] IL6STAT3;
        vector[D] IL6AMP;
        vector[D] cytok;
    }
    parameters {
       real<lower=0> mu_U_SARS_Ang; 
       real<lower=0> sigma_U_SARS_Ang;
       real beta0_U_SARS_AngToSARS_COV2;
       real<lower=0> beta_U_SARS_AngToSARS_COV2;
       real beta0_SARS_COV2ToACE2;
       real<upper=0> beta_SARS_COV2ToACE2;
       real beta0_ACE2_and_U_SARS_Ang_ToAng;
       real<upper=0> beta_ACE2ToAng;
       real<lower=0> beta_U_SARS_AngToAng;
       real beta0_AngToAGTR1;
       real<lower=0> beta_AngToAGTR1;
       real<lower=0> mu_U_ADAM17_Sil6r;
       real<lower=0> sigma_U_ADAM17_Sil6r;
       real beta0_AGTR1_UToADAM17;
       real<lower=0> beta_AGTR1ToADAM17;
       real<lower=0> beta_U_ADAM17_Sil6rToADAM17;
       real<lower=0> mu_Toci;
       real<lower=0> sigma_Toci;
       real beta0_ADAM17_U_TociToSil6r;
       real<lower=0> beta_ADAM17ToSil6r;
       real<lower=0> beta_UToSil6r;
       real<upper=0> beta_TociToSil6r;
       real<lower=0> mu_U_EGF_EGFR;
       real<lower=0> sigma_U_EGF_EGFR;
       real beta0_ADAM17_UToEGF;
       real<lower=0> beta_ADAM17ToEGF;
       real<lower=0> beta_UToEGF;
       real<lower=0> mu_U_EGFR_TNF;
       real<lower=0> sigma_U_EGFR_TNF;
       real beta0_ADAM17_UToTNF;
       real<lower=0> beta_ADAM17ToTNF;
       real<lower=0> beta_UToTNF;
       real<lower=0> mu_U_EGFR_IL6STAT3;
       real<lower=0> sigma_U_EGFR_IL6STAT3;
       real beta0_EGF_3U;
       real<lower=0> beta_EGFToEGFR;
       real<lower=0> beta_U1ToEGFR;
       real<lower=0> beta_U2ToEGFR;
       real<lower=0> beta_U3ToEGFR; 
       real<lower=0> mu_U_PRR_NFKB;
       real<lower=0> sigma_U_PRR_NFKB;
       real beta0_SARS_UPRR;
       real<lower=0> beta_SARS_COV2ToPRR;
       real<lower=0> beta_UToPRR;
       real beta0_PRR_U_EGFR_TNFToNFKB;
       real<lower=0> beta_PRRToNFKB;
       real<lower=0> beta_UToNFKB;
       real<lower=0> beta_EGFRToNFKB;
       real<lower=0> beta_TNFToNFKB;
       real beta0_NFKB_IL6STSTToIL6STAT3;
       real<lower=0> beta_UToIL6STAT3;
       real<lower=0> beta_Sil6rToIL6STAT3;
       real beta0_NFKB_IL6STATToIL6AMP;
       real<lower=0> beta_NFKBToIL6AMP;
       real<lower=0> beta_IL6STAT3ToIL6AMP;
       real<upper=0> beta0_IL6AMPTocytok;
       real<lower=0> beta_IL6AMPTocytok;
       vector[D] U_SARS_Ang;
       vector[D] U_ADAM17_Sil6r;
       vector[D] U_EGF_EGFR;
       vector[D] U_EGFR_TNF;
       vector[D] U_EGFR_IL6STAT3;
       vector[D] U_PRR_NFKB;
    }
    transformed parameters {
      vector[D] SARS_COV2_loc;
      vector[D] ACE2_loc;
      vector[D] Ang_loc;
      vector[D] AGTR1_loc;
      vector[D] ADAM17_loc;
      vector[D] Sil6r_loc;
      vector[D] EGF_loc;
      vector[D] TNF_loc;
      vector[D] EGFR_loc;
      vector[D] PRR_loc;
      vector[D] NFKB_loc;
      vector[D] IL6STAT3_loc;
      vector[D] IL6AMP_loc;
      vector[D] cytok_loc;
      for (i in 1:D){
        SARS_COV2_loc[i] = 100 / (1 + exp(-beta0_U_SARS_AngToSARS_COV2 -U_SARS_Ang[i] * beta_U_SARS_AngToSARS_COV2));
        ACE2_loc[i] = beta0_SARS_COV2ToACE2 + SARS_COV2[i] * beta_SARS_COV2ToACE2;
        Ang_loc[i] = beta0_ACE2_and_U_SARS_Ang_ToAng + ACE2[i] * beta_ACE2ToAng + U_SARS_Ang[i] * beta_U_SARS_AngToAng;
        AGTR1_loc[i] = 100 / (1 + exp(-beta0_AngToAGTR1 - Ang[i] * beta_AngToAGTR1));
        ADAM17_loc[i] = 100 / (1 + exp(-beta0_AGTR1_UToADAM17 - AGTR1[i] * beta_AGTR1ToADAM17 - U_ADAM17_Sil6r[i] * beta_U_ADAM17_Sil6rToADAM17));
        Sil6r_loc[i] = 100 / (1 + exp(-beta0_ADAM17_U_TociToSil6r - ADAM17[i] * beta_ADAM17ToSil6r - U_ADAM17_Sil6r[i] * beta_UToSil6r - Toci[i] * beta_TociToSil6r));
        EGF_loc[i] = 100 / (1 + exp(-beta0_ADAM17_UToEGF - ADAM17[i] * beta_ADAM17ToEGF - U_EGF_EGFR[i] * beta_UToEGF));
        TNF_loc[i] = 100 / (1 + exp(-beta0_ADAM17_UToTNF - ADAM17[i] * beta_ADAM17ToTNF - U_EGFR_TNF[i] * beta_UToTNF));
        EGFR_loc[i] = 100 / (1 + exp(-beta0_EGF_3U - EGF[i] * beta_EGFToEGFR - U_EGFR_IL6STAT3[i] * beta_U1ToEGFR - U_EGFR_TNF[i] * beta_U2ToEGFR  - U_EGF_EGFR[i] * beta_U3ToEGFR));
        PRR_loc[i] = 100 / (1 + exp(-beta0_SARS_UPRR - SARS_COV2[i] * beta_SARS_COV2ToPRR - U_PRR_NFKB[i] * beta_UToPRR));
        NFKB_loc[i] = 100 / (1 + exp(-beta0_PRR_U_EGFR_TNFToNFKB - PRR[i] * beta_PRRToNFKB - U_PRR_NFKB[i] * beta_UToNFKB - EGFR[i] * beta_EGFRToNFKB  - TNF[i] * beta_TNFToNFKB));
        IL6STAT3_loc[i] = 100 / (1 + exp(-beta0_NFKB_IL6STSTToIL6STAT3 - U_EGFR_IL6STAT3[i] * beta_UToIL6STAT3 - Sil6r[i] * beta_Sil6rToIL6STAT3));
        IL6AMP_loc[i] = 100 / (1 + exp(-beta0_NFKB_IL6STATToIL6AMP - NFKB[i] * beta_NFKBToIL6AMP - IL6STAT3[i] * beta_IL6STAT3ToIL6AMP));
        cytok_loc[i] = 100 / (1 + exp(-beta0_IL6AMPTocytok - IL6AMP[i] * beta_IL6AMPTocytok));
      }
    }
    model {
        mu_U_SARS_Ang ~ normal(45, 1); 
        sigma_U_SARS_Ang ~ normal(10, 1); 
        beta0_U_SARS_AngToSARS_COV2 ~ normal(0, 10);
        beta_U_SARS_AngToSARS_COV2 ~ normal(0,10);
        beta0_SARS_COV2ToACE2 ~ normal(20,10);
        beta_SARS_COV2ToACE2 ~ normal(0,10);
        beta0_ACE2_and_U_SARS_Ang_ToAng ~ normal(20,10);
        beta_ACE2ToAng ~ normal(0,10);
        beta_U_SARS_AngToAng ~ normal(0,10);
        beta0_AngToAGTR1 ~ normal(0,10);
        beta_AngToAGTR1 ~ normal(0,10);
        beta0_AGTR1_UToADAM17 ~ normal(0,10);
        beta_AGTR1ToADAM17 ~ normal(0,10);
        beta_U_ADAM17_Sil6rToADAM17 ~ normal(0,10);
        mu_Toci ~ normal(45, 1);
        sigma_Toci ~ normal(10, 1);
        beta0_ADAM17_U_TociToSil6r ~ normal(0, 10);
        beta_ADAM17ToSil6r ~ normal(0, 10);
        beta_UToSil6r ~ normal(0, 10);
        beta_TociToSil6r ~ normal(0, 10);
        mu_U_EGF_EGFR ~ normal(50,1);
        sigma_U_EGF_EGFR ~ normal(10,1);
        beta0_ADAM17_UToEGF ~ normal(0,10);
        beta_ADAM17ToEGF ~ normal(0,10);
        beta_UToEGF ~ normal(0,10);
        mu_U_EGFR_TNF ~ normal(45,1);
        sigma_U_EGFR_TNF ~ normal(10,1);
        beta0_ADAM17_UToTNF ~ normal(0, 10);
        beta_ADAM17ToTNF ~ normal(0, 10);
        beta_UToTNF ~ normal(0, 10);
        mu_U_EGFR_IL6STAT3 ~ normal(40,1);
        sigma_U_EGFR_IL6STAT3 ~ normal(10,1);
        beta0_EGF_3U ~ normal(0, 10);
        beta_EGFToEGFR ~ normal(0, 10);
        beta_U1ToEGFR ~ normal(0, 10);
        beta_U2ToEGFR ~ normal(0, 10);
        beta_U3ToEGFR ~ normal(0, 10); 
        mu_U_PRR_NFKB ~ normal(40, 1);
        sigma_U_PRR_NFKB ~ normal(10,1);
        beta0_SARS_UPRR ~ normal(0, 10);
        beta_SARS_COV2ToPRR ~ normal(0, 10);
        beta_UToPRR ~ normal(0, 10);
        beta_PRRToNFKB ~ normal(0, 10);
        beta_UToNFKB ~ normal(0, 10);
        beta_EGFRToNFKB ~ normal(0, 10);
        beta_TNFToNFKB ~ normal(0, 10);
        beta0_NFKB_IL6STSTToIL6STAT3 ~ normal(0, 10);
        beta_UToIL6STAT3 ~ normal(0, 10);
        beta_Sil6rToIL6STAT3 ~ normal(0, 10);
        beta0_NFKB_IL6STATToIL6AMP ~ normal(0, 10);
        beta_NFKBToIL6AMP ~ normal(0, 10);
        beta_IL6STAT3ToIL6AMP ~ normal(0, 10); 
        beta0_IL6AMPTocytok ~ normal(0, 10);
        beta_IL6AMPTocytok ~ normal(0, 10);         
        //
        U_SARS_Ang ~ normal(mu_U_SARS_Ang, sigma_U_SARS_Ang);      // likelihood
        SARS_COV2 ~ normal(SARS_COV2_loc, 101);
        ACE2 ~ normal(ACE2_loc,1.6);
        Ang ~ normal(Ang_loc,6);
        AGTR1 ~ normal(AGTR1_loc,7.6);
        ADAM17 ~ normal(ADAM17_loc,8.7);
        U_ADAM17_Sil6r ~ normal(mu_U_ADAM17_Sil6r, sigma_U_ADAM17_Sil6r);
        Toci ~ normal(mu_Toci, sigma_Toci);
        Sil6r ~ normal(Sil6r_loc,17.9);
        U_EGF_EGFR ~ normal(mu_U_EGF_EGFR, sigma_U_EGF_EGFR);
        EGF ~ normal(EGF_loc,7);
        U_EGFR_TNF ~ normal(mu_U_EGFR_TNF,sigma_U_EGFR_TNF);
        TNF ~ normal(TNF_loc, 6.5);
        U_EGFR_IL6STAT3 ~ normal(mu_U_EGFR_IL6STAT3, sigma_U_EGFR_IL6STAT3);
        EGFR ~ normal(EGFR_loc, 13.3);
        U_PRR_NFKB ~ normal(mu_U_PRR_NFKB,sigma_U_PRR_NFKB);
        PRR ~ normal(PRR_loc,14.1);
        NFKB ~ normal(NFKB_loc,10);
        IL6STAT3 ~ normal(IL6STAT3_loc, 18.6);
        IL6AMP ~ normal(IL6AMP_loc, 12);
        cytok ~ normal(cytok_loc, 16.2);
    }
"
```

```{r, message=FALSE, warning=FALSE}
mod <- rstan::stan_model(model_code = model_str_covid)
```

```{r, echo = FALSE}
#If you get this error (Cluster setup failed. 2 of 2 workers failed to connect.) run these lines:
if (Sys.getenv("RSTUDIO") == "1" && !nzchar(Sys.getenv("RSTUDIO_TERM")) &&
    Sys.info()["sysname"] == "Darwin") {
  parallel:::setDefaultClusterOptions(setup_strategy = "sequential")
}

data_list <- list(D=D
                  ,SARS_COV2 = observational_data$SARS_COV2[1:D]
                  ,ACE2 = observational_data$ACE2[1:D]
                  ,Ang = observational_data$Ang[1:D]
                  ,AGTR1 = observational_data$AGTR1[1:D]
                  ,ADAM17 = observational_data$ADAM17[1:D]
                  ,Toci = observational_data$Toci[1:D]
                  ,Sil6r = observational_data$Sil6r[1:D]
                  ,EGF = observational_data$EGF[1:D]
                  ,TNF = observational_data$TNF[1:D]
                  ,EGFR = observational_data$EGFR[1:D]
                  ,PRR = observational_data$PRR[1:D]
                  ,NFKB = observational_data$NFKB[1:D]
                  ,IL6STAT3= observational_data$IL6STAT3[1:D]
                  ,IL6AMP = observational_data$IL6AMP[1:D]
                  ,cytok = observational_data$cytok[1:D]
                  )
```

```{r}
hmc_fit <- rstan::sampling(mod, data=data_list, chains = 2, iter = 4000, warmup = 2000, seed = 2, control = list(max_treedepth = 15, adapt_delta = 0.99)
                           ) #seed 1
```


```{r}
stan_trace(pars = "mu_U_SARS_Ang", hmc_fit)
stan_trace(pars = "sigma_U_SARS_Ang", hmc_fit)
stan_trace(pars = "beta0_U_SARS_AngToSARS_COV2", hmc_fit)
stan_trace(pars = "beta_U_SARS_AngToSARS_COV2", hmc_fit)
stan_trace(pars = "beta0_SARS_COV2ToACE2", hmc_fit)
stan_trace(pars = "beta_SARS_COV2ToACE2", hmc_fit)
stan_trace(pars = "beta0_ACE2_and_U_SARS_Ang_ToAng", hmc_fit)
stan_trace(pars = "beta_ACE2ToAng", hmc_fit)
stan_trace(pars = "beta_U_SARS_AngToAng", hmc_fit)
stan_trace(pars = "beta0_AngToAGTR1", hmc_fit)
stan_trace(pars = "beta_AngToAGTR1", hmc_fit)
stan_trace(pars = "beta0_AGTR1_UToADAM17", hmc_fit)
stan_trace(pars = "beta_AGTR1ToADAM17", hmc_fit)        
stan_trace(pars = "beta_U_ADAM17_Sil6rToADAM17", hmc_fit)
stan_trace(pars = "mu_Toci", hmc_fit)
stan_trace(pars = "sigma_Toci", hmc_fit)
stan_trace(pars = "beta0_ADAM17_U_TociToSil6r", hmc_fit)
stan_trace(pars = "beta_ADAM17ToSil6r", hmc_fit)
stan_trace(pars = "beta_UToSil6r", hmc_fit)
stan_trace(pars = "beta_TociToSil6r", hmc_fit)
stan_trace(pars = "mu_U_EGF_EGFR", hmc_fit)
stan_trace(pars = "sigma_U_EGF_EGFR", hmc_fit)
stan_trace(pars = "beta0_ADAM17_UToEGF", hmc_fit)
stan_trace(pars = "beta_ADAM17ToEGF", hmc_fit)
stan_trace(pars = "beta_UToEGF", hmc_fit)
stan_trace(pars = "mu_U_EGFR_TNF", hmc_fit)
stan_trace(pars = "sigma_U_EGFR_TNF", hmc_fit)
stan_trace(pars = "beta0_ADAM17_UToTNF", hmc_fit)
stan_trace(pars = "beta_ADAM17ToTNF", hmc_fit)
stan_trace(pars = "beta_UToTNF", hmc_fit)
stan_trace(pars = "mu_U_EGFR_IL6STAT3", hmc_fit)
stan_trace(pars = "sigma_U_EGFR_IL6STAT3", hmc_fit)
stan_trace(pars = "beta0_EGF_3U", hmc_fit)
stan_trace(pars = "beta_EGFToEGFR", hmc_fit)
stan_trace(pars = "beta_U1ToEGFR", hmc_fit)
stan_trace(pars = "beta_U2ToEGFR", hmc_fit)
stan_trace(pars = "beta_U3ToEGFR", hmc_fit)
stan_trace(pars = "mu_U_PRR_NFKB", hmc_fit)
stan_trace(pars = "sigma_U_PRR_NFKB", hmc_fit)
stan_trace(pars = "beta0_SARS_UPRR", hmc_fit)
stan_trace(pars = "beta_SARS_COV2ToPRR", hmc_fit)
stan_trace(pars = "beta_UToPRR", hmc_fit)
stan_trace(pars = "beta0_PRR_U_EGFR_TNFToNFKB", hmc_fit)
stan_trace(pars = "beta_PRRToNFKB", hmc_fit)
stan_trace(pars = "beta_UToNFKB", hmc_fit)
stan_trace(pars = "beta_EGFRToNFKB", hmc_fit)
stan_trace(pars = "beta_TNFToNFKB", hmc_fit)
stan_trace(pars = "beta0_NFKB_IL6STSTToIL6STAT3", hmc_fit)
stan_trace(pars = "beta_UToIL6STAT3", hmc_fit)
stan_trace(pars = "beta_Sil6rToIL6STAT3", hmc_fit)
stan_trace(pars = "beta0_NFKB_IL6STATToIL6AMP", hmc_fit)
stan_trace(pars = "beta_NFKBToIL6AMP", hmc_fit)
stan_trace(pars = "beta_IL6STAT3ToIL6AMP", hmc_fit)
stan_trace(pars = "beta0_IL6AMPTocytok", hmc_fit)
stan_trace(pars = "beta_IL6AMPTocytok", hmc_fit)
```

Now let's extract the samples:

```{r}
#hmc_fit <- knocker::hmc_fit_covid_D200_hmcseed2

samples <- rstan::extract(hmc_fit, c("mu_U_SARS_Ang", "sigma_U_SARS_Ang"
                                     ,"beta0_U_SARS_AngToSARS_COV2","beta_U_SARS_AngToSARS_COV2"
                                     ,"beta0_SARS_COV2ToACE2", "beta_SARS_COV2ToACE2"
                                     ,"beta0_ACE2_and_U_SARS_Ang_ToAng", "beta_ACE2ToAng", "beta_U_SARS_AngToAng"
                                     ,"beta0_AngToAGTR1", "beta_AngToAGTR1"
                                     ,"mu_U_ADAM17_Sil6r", "sigma_U_ADAM17_Sil6r"
                                     ,"beta0_AGTR1_UToADAM17", "beta_AGTR1ToADAM17","beta_U_ADAM17_Sil6rToADAM17"
                                     ,"mu_Toci", "sigma_Toci"
                                     ,"beta0_ADAM17_U_TociToSil6r", "beta_ADAM17ToSil6r", "beta_UToSil6r", "beta_TociToSil6r"
                                     ,"mu_U_EGF_EGFR", "sigma_U_EGF_EGFR"
                                     ,"beta0_ADAM17_UToEGF", "beta_ADAM17ToEGF", "beta_UToEGF"
                                     ,"mu_U_EGFR_TNF", "sigma_U_EGFR_TNF"
                                     ,"beta0_ADAM17_UToTNF", "beta_ADAM17ToTNF", "beta_UToTNF"
                                     ,"mu_U_EGFR_IL6STAT3", "sigma_U_EGFR_IL6STAT3"
                                     ,"beta0_EGF_3U", "beta_EGFToEGFR", "beta_U1ToEGFR", "beta_U2ToEGFR", "beta_U3ToEGFR"
                                     ,"mu_U_PRR_NFKB", "sigma_U_PRR_NFKB"
                                     ,"beta0_SARS_UPRR", "beta_SARS_COV2ToPRR", "beta_UToPRR"
                                     ,"beta0_PRR_U_EGFR_TNFToNFKB", "beta_PRRToNFKB", "beta_UToNFKB", "beta_EGFRToNFKB", "beta_TNFToNFKB"  
                                     ,"beta0_NFKB_IL6STSTToIL6STAT3", "beta_UToIL6STAT3", "beta_Sil6rToIL6STAT3"
                                     ,"beta0_NFKB_IL6STATToIL6AMP", "beta_NFKBToIL6AMP", "beta_IL6STAT3ToIL6AMP"
                                     ,"beta0_IL6AMPTocytok", "beta_IL6AMPTocytok"
                                     )
                          )
print("mu_U_SARS_Ang")
mean(samples$mu_U_SARS_Ang)
mu_U_SARS_Ang
print("sigma_U_SARS_Ang")
mean(samples$sigma_U_SARS_Ang)
sigma_U_SARS_Ang

print("beta0_U_SARS_AngToSARS_COV2")
mean(samples$beta0_U_SARS_AngToSARS_COV2)
beta0_U_SARS_AngToSARS_COV2
print("beta_U_SARS_AngToSARS_COV2")
mean(samples$beta_U_SARS_AngToSARS_COV2)
beta_U_SARS_AngToSARS_COV2

print("beta0_SARS_COV2ToACE2")
mean(samples$beta0_SARS_COV2ToACE2)
beta0_SARS_COV2ToACE2
print("beta_SARS_COV2ToACE2")
mean(samples$beta_SARS_COV2ToACE2)
beta_SARS_COV2ToACE2

print("beta0_ACE2_and_U_SARS_Ang_ToAng")
mean(samples$beta0_ACE2_and_U_SARS_Ang_ToAng)
beta0_ACE2_and_U_SARS_Ang_ToAng
print("beta_ACE2ToAng")
mean(samples$beta_ACE2ToAng)
beta_ACE2ToAng
print("beta_U_SARS_AngToAng")
mean(samples$beta_U_SARS_AngToAng)
beta_U_SARS_AngToAng  

print("mu_U_ADAM17_Sil6r")
mean(samples$mu_U_ADAM17_Sil6r)
mu_U_ADAM17_Sil6r
print("sigma_U_ADAM17_Sil6r")
mean(samples$sigma_U_ADAM17_Sil6r)
sigma_U_ADAM17_Sil6r

print("beta0_AGTR1_UToADAM17")
mean(samples$beta0_AGTR1_UToADAM17)
beta0_AGTR1_UToADAM17
print("beta_AGTR1ToADAM17")
mean(samples$beta_AGTR1ToADAM17)
beta_AGTR1ToADAM17
print("beta_U_ADAM17_Sil6rToADAM17")
mean(samples$beta_U_ADAM17_Sil6rToADAM17)
beta_U_ADAM17_Sil6rToADAM17

print("mu_Toci")
mean(samples$mu_Toci)
mu_Toci
print("sigma_Toci")
mean(samples$sigma_Toci)
sigma_Toci

print("beta0_ADAM17_U_TociToSil6r")
mean(samples$beta0_ADAM17_U_TociToSil6r)
beta0_ADAM17_U_TociToSil6r
print("beta_ADAM17ToSil6r")
mean(samples$beta_ADAM17ToSil6r)
beta_ADAM17ToSil6r
print("beta_UToSil6r")
mean(samples$beta_UToSil6r)
beta_UToSil6r
print("beta_TociToSil6r")
mean(samples$beta_TociToSil6r)
beta_TociToSil6r

print("mu_U_EGF_EGFR")
mean(samples$mu_U_EGF_EGFR)
mu_U_EGF_EGFR
print("sigma_U_EGF_EGFR")
mean(samples$sigma_U_EGF_EGFR)
sigma_U_EGF_EGFR

print("beta0_ADAM17_UToEGF")
mean(samples$beta0_ADAM17_UToEGF)
beta0_ADAM17_UToEGF
print("beta_ADAM17ToEGF")
mean(samples$beta_ADAM17ToEGF)
beta_ADAM17ToEGF
print("beta_UToEGF")
mean(samples$beta_UToEGF)
beta_UToEGF

print("mu_U_EGFR_TNF")
mean(samples$mu_U_EGFR_TNF)
mu_U_EGFR_TNF
print("sigma_U_EGFR_TNF")
mean(samples$sigma_U_EGFR_TNF)
sigma_U_EGFR_TNF

print("beta0_ADAM17_UToTNF")
mean(samples$beta0_ADAM17_UToTNF)
beta0_ADAM17_UToTNF
print("beta_ADAM17ToTNF")
mean(samples$beta_ADAM17ToTNF)
beta_ADAM17ToTNF
print("beta_UToTNF")
mean(samples$beta_UToTNF)
beta_UToTNF

print("mu_U_EGFR_IL6STAT3")
mean(samples$mu_U_EGFR_IL6STAT3)
mu_U_EGFR_IL6STAT3
print("sigma_U_EGFR_IL6STAT3")
mean(samples$sigma_U_EGFR_IL6STAT3)
sigma_U_EGFR_IL6STAT3

print("beta0_EGF_3U")
mean(samples$beta0_EGF_3U)
beta0_EGF_3U
print("beta_EGFToEGFR")
mean(samples$beta_EGFToEGFR)
beta_EGFToEGFR
print("beta_U1ToEGFR")
mean(samples$beta_U1ToEGFR)
beta_U1ToEGFR
print("beta_U2ToEGFR")
mean(samples$beta_U2ToEGFR)
beta_U2ToEGFR
print("beta_U3ToEGFR")
mean(samples$beta_U3ToEGFR)
beta_U3ToEGFR

mean(samples$mu_U_PRR_NFKB)
mu_U_PRR_NFKB
mean(samples$sigma_U_PRR_NFKB)
sigma_U_PRR_NFKB

mean(samples$beta0_SARS_UPRR)
beta0_SARS_UPRR
mean(samples$beta_SARS_COV2ToPRR)
beta_SARS_COV2ToPRR
mean(samples$beta_UToPRR)
beta_UToPRR

mean(samples$beta0_PRR_U_EGFR_TNFToNFKB)
beta0_PRR_U_EGFR_TNFToNFKB
mean(samples$beta_PRRToNFKB)
beta_PRRToNFKB
mean(samples$beta_UToNFKB)
beta_UToNFKB
mean(samples$beta_EGFRToNFKB)
beta_EGFRToNFKB
mean(samples$beta_TNFToNFKB)
beta_TNFToNFKB

mean(samples$beta0_NFKB_IL6STSTToIL6STAT3)
beta0_NFKB_IL6STSTToIL6STAT3
mean(samples$beta_UToIL6STAT3)
beta_UToIL6STAT3
mean(samples$beta_Sil6rToIL6STAT3)
beta_Sil6rToIL6STAT3

mean(samples$beta0_NFKB_IL6STATToIL6AMP)
beta0_NFKB_IL6STATToIL6AMP
mean(samples$beta_NFKBToIL6AMP)
beta_NFKBToIL6AMP
mean(samples$beta_IL6STAT3ToIL6AMP)
beta_IL6STAT3ToIL6AMP

mean(samples$beta0_IL6AMPTocytok)
beta0_IL6AMPTocytok
mean(samples$beta_IL6AMPTocytok)
beta_IL6AMPTocytok
```

# Consistency plots

```{r}
num_samples = 1000
model <- function(mu_U_SARS_Ang, sigma_U_SARS_Ang
                            ,beta0_U_SARS_AngToSARS_COV2,beta_U_SARS_AngToSARS_COV2
                            ,beta0_SARS_COV2ToACE2, beta_SARS_COV2ToACE2
                            ,beta0_ACE2_and_U_SARS_Ang_ToAng, beta_ACE2ToAng, beta_U_SARS_AngToAng
                            ,beta0_AngToAGTR1, beta_AngToAGTR1
                            ,mu_U_ADAM17_Sil6r,sigma_U_ADAM17_Sil6r
                            ,beta0_AGTR1_UToADAM17,beta_AGTR1ToADAM17, beta_U_ADAM17_Sil6rToADAM17
                            ,mu_Toci, sigma_Toci
                            ,beta0_ADAM17_U_TociToSil6r, beta_ADAM17ToSil6r, beta_UToSil6r, beta_TociToSil6r
                            ,mu_U_EGF_EGFR, sigma_U_EGF_EGFR
                            ,beta0_ADAM17_UToEGF, beta_ADAM17ToEGF, beta_UToEGF
                            ,mu_U_EGFR_TNF, sigma_U_EGFR_TNF
                            ,beta0_ADAM17_UToTNF, beta_ADAM17ToTNF, beta_UToTNF
                            ,mu_U_EGFR_IL6STAT3,sigma_U_EGFR_IL6STAT3
                            ,beta0_EGF_3U, beta_EGFToEGFR, beta_U1ToEGFR, beta_U2ToEGFR, beta_U3ToEGFR
                            ,mu_U_PRR_NFKB, sigma_U_PRR_NFKB
                            ,beta0_SARS_UPRR, beta_SARS_COV2ToPRR, beta_UToPRR
                            ,beta0_PRR_U_EGFR_TNFToNFKB, beta_PRRToNFKB, beta_UToNFKB, beta_EGFRToNFKB, beta_TNFToNFKB
                            ,beta0_NFKB_IL6STSTToIL6STAT3, beta_UToIL6STAT3, beta_Sil6rToIL6STAT3
                            ,beta0_NFKB_IL6STATToIL6AMP, beta_NFKBToIL6AMP, beta_IL6STAT3ToIL6AMP
                            ,beta0_IL6AMPTocytok, beta_IL6AMPTocytok
) {
    U_SARS_Ang_1 <- rnorm(num_samples, mu_U_SARS_Ang, sigma_U_SARS_Ang)
    SARS_COV2_1 = rnorm(num_samples,100 / (1 + exp(-beta0_U_SARS_AngToSARS_COV2 - U_SARS_Ang_1 * beta_U_SARS_AngToSARS_COV2)), sqrt(var(SARS_COV2)))
    ACE2_1 = rnorm(num_samples, beta0_SARS_COV2ToACE2 + SARS_COV2_1 * beta_SARS_COV2ToACE2, sqrt(var(ACE2)))
    Ang_1 = rnorm(num_samples, beta0_ACE2_and_U_SARS_Ang_ToAng + ACE2_1 * beta_ACE2ToAng + U_SARS_Ang_1 *beta_U_SARS_AngToAng, sqrt(var(Ang)))
    AGTR1_1 = rnorm(num_samples, 100 / (1 + exp(-beta0_AngToAGTR1 - Ang_1 * beta_AngToAGTR1)), sqrt(var(AGTR1)))
    U_ADAM17_Sil6r_1 = rnorm(num_samples,mu_U_ADAM17_Sil6r,sigma_U_ADAM17_Sil6r)
    ADAM17_1 = rnorm(num_samples, 100 / (1 + exp(-beta0_AGTR1_UToADAM17 - AGTR1_1 * beta_AGTR1ToADAM17 - U_ADAM17_Sil6r_1 * beta_U_ADAM17_Sil6rToADAM17)), sqrt(var(ADAM17)))
    Toci_1 = rnorm(num_samples,mu_Toci, sigma_Toci)
    
    Sil6r_1 = rnorm(num_samples, 100 / (1 + exp(-beta0_ADAM17_U_TociToSil6r - ADAM17_1 * beta_ADAM17ToSil6r - U_ADAM17_Sil6r_1 * beta_UToSil6r - Toci_1 * beta_TociToSil6r)), sqrt(var(observational_data$Sil6r)))
    
    U_EGF_EGFR_1 = rnorm(num_samples, mu_U_EGF_EGFR, sigma_U_EGF_EGFR)
    EGF_1 = rnorm(num_samples, 100 / (1 + exp(-beta0_ADAM17_UToEGF - ADAM17_1 * beta_ADAM17ToEGF - U_EGF_EGFR_1 * beta_UToEGF)), sqrt(var(EGF)))
    U_EGFR_TNF_1 = rnorm(num_samples, mu_U_EGFR_TNF, sigma_U_EGFR_TNF)
    TNF_1 = rnorm(num_samples, 100 / (1 + exp(-beta0_ADAM17_UToTNF - ADAM17_1 * beta_ADAM17ToTNF - U_EGFR_TNF_1 * beta_UToTNF)) , sqrt(var(TNF)))
    U_EGFR_IL6STAT3_1 =  rnorm(num_samples, mu_U_EGFR_IL6STAT3, sigma_U_EGFR_IL6STAT3)
    EGFR_1 = 100 / (1 + exp(-beta0_EGF_3U - EGF_1 * beta_EGFToEGFR - U_EGFR_IL6STAT3_1 * beta_U1ToEGFR - U_EGFR_TNF_1 * beta_U2ToEGFR  - U_EGF_EGFR_1 * beta_U3ToEGFR));
    U_PRR_NFKB_1 = rnorm(num_samples, mu_U_PRR_NFKB, sigma_U_PRR_NFKB)
    PRR_1 = rnorm(num_samples,100 / (1 + exp(-beta0_SARS_UPRR - SARS_COV2_1 * beta_SARS_COV2ToPRR - U_PRR_NFKB_1 * beta_UToPRR)) , sqrt(var(PRR)))
    NFKB_1 = rnorm(num_samples,100 / (1 + exp(-beta0_PRR_U_EGFR_TNFToNFKB - PRR_1 * beta_PRRToNFKB - U_PRR_NFKB_1 * beta_UToNFKB - EGFR_1 * beta_EGFRToNFKB  - TNF_1 * beta_TNFToNFKB)) ,sqrt(var(NFKB)))
    IL6STAT3_1 = rnorm(num_samples,100 / (1 + exp(-beta0_NFKB_IL6STSTToIL6STAT3 - U_EGFR_IL6STAT3_1 * beta_UToIL6STAT3 - Sil6r_1 * beta_Sil6rToIL6STAT3)), sqrt(var(IL6STAT3)))
    IL6AMP_1 = rnorm(num_samples,100 / (1 + exp(-beta0_NFKB_IL6STATToIL6AMP - NFKB_1 * beta_NFKBToIL6AMP - IL6STAT3_1 * beta_IL6STAT3ToIL6AMP)), sqrt(var(IL6AMP)))
    cytok_1 = rnorm(num_samples,100 / (1 + exp(-beta0_IL6AMPTocytok - IL6AMP_1 * beta_IL6AMPTocytok)), sqrt(var(cytok)))
    return(cytok_1)
}

mutilated_model <- function(mu_U_SARS_Ang, sigma_U_SARS_Ang
                            ,beta0_U_SARS_AngToSARS_COV2,beta_U_SARS_AngToSARS_COV2
                            ,beta0_SARS_COV2ToACE2, beta_SARS_COV2ToACE2
                            ,beta0_ACE2_and_U_SARS_Ang_ToAng, beta_ACE2ToAng, beta_U_SARS_AngToAng
                            ,beta0_AngToAGTR1, beta_AngToAGTR1
                            ,mu_U_ADAM17_Sil6r,sigma_U_ADAM17_Sil6r
                            ,beta0_AGTR1_UToADAM17,beta_AGTR1ToADAM17, beta_U_ADAM17_Sil6rToADAM17
                            ,mu_Toci, sigma_Toci
                            ,beta0_ADAM17_U_TociToSil6r, beta_ADAM17ToSil6r, beta_UToSil6r, beta_TociToSil6r
                            ,mu_U_EGF_EGFR, sigma_U_EGF_EGFR
                            ,beta0_ADAM17_UToEGF, beta_ADAM17ToEGF, beta_UToEGF
                            ,mu_U_EGFR_TNF, sigma_U_EGFR_TNF
                            ,beta0_ADAM17_UToTNF, beta_ADAM17ToTNF, beta_UToTNF
                            ,mu_U_EGFR_IL6STAT3,sigma_U_EGFR_IL6STAT3
                            ,beta0_EGF_3U, beta_EGFToEGFR, beta_U1ToEGFR, beta_U2ToEGFR, beta_U3ToEGFR
                            ,mu_U_PRR_NFKB, sigma_U_PRR_NFKB
                            ,beta0_SARS_UPRR, beta_SARS_COV2ToPRR, beta_UToPRR
                            ,beta0_PRR_U_EGFR_TNFToNFKB, beta_PRRToNFKB, beta_UToNFKB, beta_EGFRToNFKB, beta_TNFToNFKB
                            ,beta0_NFKB_IL6STSTToIL6STAT3, beta_UToIL6STAT3, beta_Sil6rToIL6STAT3
                            ,beta0_NFKB_IL6STATToIL6AMP, beta_NFKBToIL6AMP, beta_IL6STAT3ToIL6AMP
                            ,beta0_IL6AMPTocytok, beta_IL6AMPTocytok
) {
    U_SARS_Ang_1 <- rnorm(num_samples, mu_U_SARS_Ang, sigma_U_SARS_Ang)
    SARS_COV2_1 = rnorm(num_samples,100 / (1 + exp(-beta0_U_SARS_AngToSARS_COV2 - U_SARS_Ang_1 * beta_U_SARS_AngToSARS_COV2)), sqrt(var(SARS_COV2)))
    ACE2_1 = rnorm(num_samples, beta0_SARS_COV2ToACE2 + SARS_COV2_1 * beta_SARS_COV2ToACE2, sqrt(var(ACE2)))
    Ang_1 = rnorm(num_samples, beta0_ACE2_and_U_SARS_Ang_ToAng + ACE2_1 * beta_ACE2ToAng + U_SARS_Ang_1 *beta_U_SARS_AngToAng, sqrt(var(Ang)))
    AGTR1_1 = rnorm(num_samples, 100 / (1 + exp(-beta0_AngToAGTR1 - Ang_1 * beta_AngToAGTR1)), sqrt(var(AGTR1)))
    U_ADAM17_Sil6r_1 = rnorm(num_samples,mu_U_ADAM17_Sil6r,sigma_U_ADAM17_Sil6r)
    ADAM17_1 = rnorm(num_samples, 100 / (1 + exp(-beta0_AGTR1_UToADAM17 - AGTR1_1 * beta_AGTR1ToADAM17 - U_ADAM17_Sil6r_1 * beta_U_ADAM17_Sil6rToADAM17)), sqrt(var(ADAM17)))
    Toci_1 = rnorm(num_samples,mu_Toci, sigma_Toci)
    
    Sil6r_1 = rep(20, num_samples)
    
    U_EGF_EGFR_1 = rnorm(num_samples, mu_U_EGF_EGFR, sigma_U_EGF_EGFR)
    EGF_1 = rnorm(num_samples, 100 / (1 + exp(-beta0_ADAM17_UToEGF - ADAM17_1 * beta_ADAM17ToEGF - U_EGF_EGFR_1 * beta_UToEGF)), sqrt(var(EGF)))
    U_EGFR_TNF_1 = rnorm(num_samples, mu_U_EGFR_TNF, sigma_U_EGFR_TNF)
    TNF_1 = rnorm(num_samples, 100 / (1 + exp(-beta0_ADAM17_UToTNF - ADAM17_1 * beta_ADAM17ToTNF - U_EGFR_TNF_1 * beta_UToTNF)) , sqrt(var(TNF)))
    U_EGFR_IL6STAT3_1 =  rnorm(num_samples, mu_U_EGFR_IL6STAT3, sigma_U_EGFR_IL6STAT3)
    EGFR_1 = 100 / (1 + exp(-beta0_EGF_3U - EGF_1 * beta_EGFToEGFR - U_EGFR_IL6STAT3_1 * beta_U1ToEGFR - U_EGFR_TNF_1 * beta_U2ToEGFR  - U_EGF_EGFR_1 * beta_U3ToEGFR));
    U_PRR_NFKB_1 = rnorm(num_samples, mu_U_PRR_NFKB, sigma_U_PRR_NFKB)
    PRR_1 = rnorm(num_samples,100 / (1 + exp(-beta0_SARS_UPRR - SARS_COV2_1 * beta_SARS_COV2ToPRR - U_PRR_NFKB_1 * beta_UToPRR)) , sqrt(var(PRR)))
    NFKB_1 = rnorm(num_samples,100 / (1 + exp(-beta0_PRR_U_EGFR_TNFToNFKB - PRR_1 * beta_PRRToNFKB - U_PRR_NFKB_1 * beta_UToNFKB - EGFR_1 * beta_EGFRToNFKB  - TNF_1 * beta_TNFToNFKB)) ,sqrt(var(NFKB)))
    IL6STAT3_1 = rnorm(num_samples,100 / (1 + exp(-beta0_NFKB_IL6STSTToIL6STAT3 - U_EGFR_IL6STAT3_1 * beta_UToIL6STAT3 - Sil6r_1 * beta_Sil6rToIL6STAT3)), sqrt(var(IL6STAT3)))
    IL6AMP_1 = rnorm(num_samples,100 / (1 + exp(-beta0_NFKB_IL6STATToIL6AMP - NFKB_1 * beta_NFKBToIL6AMP - IL6STAT3_1 * beta_IL6STAT3ToIL6AMP)), sqrt(var(IL6AMP)))
    cytok_1 = rnorm(num_samples,100 / (1 + exp(-beta0_IL6AMPTocytok - IL6AMP_1 * beta_IL6AMPTocytok)), sqrt(var(cytok)))
    return(cytok_1)
}
```


```{r}
indexes = sample(length(samples$mu_U_SARS_Ang), 20, replace = FALSE)
y_grey = list()
for (i in 1:length(indexes)) {
  j = indexes[i]
  y_grey[[i]] = mutilated_model(samples$mu_U_SARS_Ang[j]
                                ,samples$sigma_U_SARS_Ang[j]
                                ,samples$beta0_U_SARS_AngToSARS_COV2[j]
                                ,samples$beta_U_SARS_AngToSARS_COV2[j]
                                ,samples$beta0_SARS_COV2ToACE2[j]
                                ,samples$beta_SARS_COV2ToACE2[j]
                                ,samples$beta0_ACE2_and_U_SARS_Ang_ToAng[j]
                                ,samples$beta_ACE2ToAng[j]
                                ,samples$beta_U_SARS_AngToAng[j]
                                ,samples$beta0_AngToAGTR1[j]
                                ,samples$beta_AngToAGTR1[j]
                                ,mu_U_ADAM17_Sil6r
                                ,sigma_U_ADAM17_Sil6r
                                ,samples$beta0_AGTR1_UToADAM17[j]
                                ,samples$beta_AGTR1ToADAM17[j]
                                ,samples$beta_U_ADAM17_Sil6rToADAM17[j]
                                ,samples$mu_Toci[j]
                                ,samples$sigma_Toci[j]
                                ,samples$beta0_ADAM17_U_TociToSil6r[j]
                                ,samples$beta_ADAM17ToSil6r[j]
                                ,samples$beta_UToSil6r[j]
                                ,samples$beta_TociToSil6r[j]
                                ,samples$mu_U_EGF_EGFR[j]
                                ,samples$sigma_U_EGF_EGFR[j]
                                ,samples$beta0_ADAM17_UToEGF[j]
                                ,samples$beta_ADAM17ToEGF[j]
                                ,samples$beta_UToEGF[j]
                                ,samples$mu_U_EGFR_TNF[j]
                                ,samples$sigma_U_EGFR_TNF[j]
                                ,samples$beta0_ADAM17_UToTNF[j]
                                ,samples$beta_ADAM17ToTNF[j]
                                ,samples$beta_UToTNF[j]
                                ,samples$mu_U_EGFR_IL6STAT3[j]
                                ,samples$sigma_U_EGFR_IL6STAT3[j]
                                ,samples$beta0_EGF_3U[j]
                                ,samples$beta_EGFToEGFR[j]
                                ,samples$beta_U1ToEGFR[j]
                                ,samples$beta_U2ToEGFR[j]
                                ,samples$beta_U3ToEGFR[j]
                                ,samples$mu_U_PRR_NFKB[j]
                                ,samples$sigma_U_PRR_NFKB[j]
                                ,samples$beta0_SARS_UPRR[j]
                                ,samples$beta_SARS_COV2ToPRR[j]
                                ,samples$beta_UToPRR[j]
                                ,samples$beta0_PRR_U_EGFR_TNFToNFKB[j]
                                ,samples$beta_PRRToNFKB[j]
                                ,samples$beta_UToNFKB[j]
                                ,samples$beta_EGFRToNFKB[j]
                                ,samples$beta_TNFToNFKB[j]
                                ,samples$beta0_NFKB_IL6STSTToIL6STAT3[j]
                                ,samples$beta_UToIL6STAT3[j]
                                ,samples$beta_Sil6rToIL6STAT3[j]
                                ,samples$beta0_NFKB_IL6STATToIL6AMP[j]
                                ,samples$beta_NFKBToIL6AMP[j]
                                ,samples$beta_IL6STAT3ToIL6AMP[j]
                                ,samples$beta0_IL6AMPTocytok[j]
                                , samples$beta_IL6AMPTocytok[j]
  )
}
```

```{r}
set.seed(1)
y_grey_mean <-  mutilated_model(mu_U_SARS_Ang = mean(samples$mu_U_SARS_Ang),
                                sigma_U_SARS_Ang = mean(samples$sigma_U_SARS_Ang),
                                beta0_U_SARS_AngToSARS_COV2 = mean(samples$beta0_U_SARS_AngToSARS_COV2),
                                beta_U_SARS_AngToSARS_COV2 = mean(samples$beta_U_SARS_AngToSARS_COV2),
                                beta0_SARS_COV2ToACE2 = mean(samples$beta0_SARS_COV2ToACE2),
                                beta_SARS_COV2ToACE2 = mean(samples$beta_SARS_COV2ToACE2),
                                beta0_ACE2_and_U_SARS_Ang_ToAng = mean(samples$beta0_ACE2_and_U_SARS_Ang_ToAng),
                                beta_ACE2ToAng = mean(samples$beta_ACE2ToAng),
                                beta_U_SARS_AngToAng = mean(samples$beta_U_SARS_AngToAng),
                                beta0_AngToAGTR1 = mean(samples$beta0_AngToAGTR1),
                                beta_AngToAGTR1 = mean(samples$beta_AngToAGTR1),
                                mu_U_ADAM17_Sil6r = mean(samples$mu_U_ADAM17_Sil6r),
                                sigma_U_ADAM17_Sil6r = mean(samples$sigma_U_ADAM17_Sil6r),
                                mean(samples$beta0_AGTR1_UToADAM17),
                                mean(samples$beta_AGTR1ToADAM17),
                                mean(samples$beta_U_ADAM17_Sil6rToADAM17),
                                mean(samples$mu_Toci),
                                mean(samples$sigma_Toci),
                                mean(samples$beta0_ADAM17_U_TociToSil6r),
                                mean(samples$beta_ADAM17ToSil6r),
                                mean(samples$beta_UToSil6r),
                                mean(samples$beta_TociToSil6r),
                                mean(samples$mu_U_EGF_EGFR),
                                mean(samples$sigma_U_EGF_EGFR),
                                mean(samples$beta0_ADAM17_UToEGF),
                                mean(samples$beta_ADAM17ToEGF),
                                mean(samples$beta_UToEGF),
                                mean(samples$mu_U_EGFR_TNF),
                                mean(samples$sigma_U_EGFR_TNF),
                                mean(samples$beta0_ADAM17_UToTNF),
                                mean(samples$beta_ADAM17ToTNF),
                                mean(samples$beta_UToTNF),
                                mean(samples$mu_U_EGFR_IL6STAT3),
                                mean(samples$sigma_U_EGFR_IL6STAT3),
                                mean(samples$beta0_EGF_3U),
                                mean(samples$beta_EGFToEGFR),
                                mean(samples$beta_U1ToEGFR),
                                mean(samples$beta_U2ToEGFR),
                                mean(samples$beta_U3ToEGFR),
                                mean(samples$mu_U_PRR_NFKB),
                                mean(samples$sigma_U_PRR_NFKB),
                                mean(samples$beta0_SARS_UPRR),
                                mean(samples$beta_SARS_COV2ToPRR),
                                mean(samples$beta_UToPRR),
                                mean(samples$beta0_PRR_U_EGFR_TNFToNFKB),
                                mean(samples$beta_PRRToNFKB),
                                mean(samples$beta_UToNFKB),
                                mean(samples$beta_EGFRToNFKB),
                                mean(samples$beta_TNFToNFKB),
                                mean(samples$beta0_NFKB_IL6STSTToIL6STAT3),
                                mean(samples$beta_UToIL6STAT3),
                                mean(samples$beta_Sil6rToIL6STAT3),
                                mean(samples$beta0_NFKB_IL6STATToIL6AMP),
                                mean(samples$beta_NFKBToIL6AMP),
                                mean(samples$beta_IL6STAT3ToIL6AMP),
                                mean(samples$beta0_IL6AMPTocytok),
                                mean(samples$beta_IL6AMPTocytok)
                                )
y_grey_mean2 <-  model(mu_U_SARS_Ang = mean(samples$mu_U_SARS_Ang),
                                sigma_U_SARS_Ang = mean(samples$sigma_U_SARS_Ang),
                                beta0_U_SARS_AngToSARS_COV2 = mean(samples$beta0_U_SARS_AngToSARS_COV2),
                                beta_U_SARS_AngToSARS_COV2 = mean(samples$beta_U_SARS_AngToSARS_COV2),
                                beta0_SARS_COV2ToACE2 = mean(samples$beta0_SARS_COV2ToACE2),
                                beta_SARS_COV2ToACE2 = mean(samples$beta_SARS_COV2ToACE2),
                                beta0_ACE2_and_U_SARS_Ang_ToAng = mean(samples$beta0_ACE2_and_U_SARS_Ang_ToAng),
                                beta_ACE2ToAng = mean(samples$beta_ACE2ToAng),
                                beta_U_SARS_AngToAng = mean(samples$beta_U_SARS_AngToAng),
                                beta0_AngToAGTR1 = mean(samples$beta0_AngToAGTR1),
                                beta_AngToAGTR1 = mean(samples$beta_AngToAGTR1),
                                mu_U_ADAM17_Sil6r = mean(samples$mu_U_ADAM17_Sil6r),
                                sigma_U_ADAM17_Sil6r = mean(samples$sigma_U_ADAM17_Sil6r),
                                mean(samples$beta0_AGTR1_UToADAM17),
                                mean(samples$beta_AGTR1ToADAM17),
                                mean(samples$beta_U_ADAM17_Sil6rToADAM17),
                                mean(samples$mu_Toci),
                                mean(samples$sigma_Toci),
                                mean(samples$beta0_ADAM17_U_TociToSil6r),
                                mean(samples$beta_ADAM17ToSil6r),
                                mean(samples$beta_UToSil6r),
                                mean(samples$beta_TociToSil6r),
                                mean(samples$mu_U_EGF_EGFR),
                                mean(samples$sigma_U_EGF_EGFR),
                                mean(samples$beta0_ADAM17_UToEGF),
                                mean(samples$beta_ADAM17ToEGF),
                                mean(samples$beta_UToEGF),
                                mean(samples$mu_U_EGFR_TNF),
                                mean(samples$sigma_U_EGFR_TNF),
                                mean(samples$beta0_ADAM17_UToTNF),
                                mean(samples$beta_ADAM17ToTNF),
                                mean(samples$beta_UToTNF),
                                mean(samples$mu_U_EGFR_IL6STAT3),
                                mean(samples$sigma_U_EGFR_IL6STAT3),
                                mean(samples$beta0_EGF_3U),
                                mean(samples$beta_EGFToEGFR),
                                mean(samples$beta_U1ToEGFR),
                                mean(samples$beta_U2ToEGFR),
                                mean(samples$beta_U3ToEGFR),
                                mean(samples$mu_U_PRR_NFKB),
                                mean(samples$sigma_U_PRR_NFKB),
                                mean(samples$beta0_SARS_UPRR),
                                mean(samples$beta_SARS_COV2ToPRR),
                                mean(samples$beta_UToPRR),
                                mean(samples$beta0_PRR_U_EGFR_TNFToNFKB),
                                mean(samples$beta_PRRToNFKB),
                                mean(samples$beta_UToNFKB),
                                mean(samples$beta_EGFRToNFKB),
                                mean(samples$beta_TNFToNFKB),
                                mean(samples$beta0_NFKB_IL6STSTToIL6STAT3),
                                mean(samples$beta_UToIL6STAT3),
                                mean(samples$beta_Sil6rToIL6STAT3),
                                mean(samples$beta0_NFKB_IL6STATToIL6AMP),
                                mean(samples$beta_NFKBToIL6AMP),
                                mean(samples$beta_IL6STAT3ToIL6AMP),
                                mean(samples$beta0_IL6AMPTocytok),
                                mean(samples$beta_IL6AMPTocytok)
                                )

```


```{r}
df_SIL6_on_cytok <- data.frame(type = c(rep("True",500),rep("LVM",500)),
                           value = c(interventional_data$cytok[1:500], y_grey_mean[1:500])) #length int data is 200
pp <- df_SIL6_on_cytok %>% ggplot( aes(x=value, fill=type, color = type)) +
    geom_histogram(color="#e9ecef", alpha=0.6, position = 'identity', bins = 20) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.line = element_line(colour = "black"),
          legend.title = element_text(color = "black", size = 18, face = "bold"),
          legend.text = element_text(color = "black", size = 14),
          axis.text=element_text(size=14),
          axis.title=element_text(size=18,face="bold"),
          legend.position = "top"
          ) +
    guides(fill=guide_legend(title="Samples of P(cytok | do(Sil6r = 20))")) +
    xlab("Samples")
pp
#ggsave("distOverCytok.pdf", plot = pp, width = 7, height = 7, dpi = 300, units = "in")
```




