---
title: "IGF case study"
author: "Sara Taheri"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(purrr)
library(rstan)
library(bayesplot)
library(ggplot2)
library(mvtnorm)
library(parallel)
library(usethis)
library(reshape2)
library(ggplot2)
library(gridExtra)
library(grid)
```


# IGF case study where IGF, EGF and PI3K are hidden

```{r}
model_str_IGF <- "
    data {
        int D;
        vector[D] SOS_train;
        vector[D] AKT_train;
        vector[D] Raf_train;
        vector[D] Mek_train;
        vector[D] Erk_train;
        vector[D] Ras_train;
    }
  parameters {
       real<lower=0> mu_EGF; 
       real<lower=0> sigma_EGF;
       real<lower=0> mu_IGF; 
       real<lower=0> sigma_IGF;
       real beta0_EGFIGFToSOS; 
       real<lower=0> beta_EGFToSOS;
       real<lower=0> beta_IGFToSOS;
       real beta0_SOSToRas;
       real<lower=0> beta_SOSToRas;
       real beta0_AKT;
       real<lower=0> beta_EGFToAKT;
       real<lower=0> beta_IGFToAKT;
       real<lower=0> beta_RasToAKT;
       real beta0_RasAKTToRaf;
       real<lower=0> beta_RasToRaf;
       real<upper=0> beta_AKTToRaf;
       real beta0_RafToMek;
       real<lower=0> beta_RafToMek;
       real beta0_MekT0Erk;
       real<lower=0> beta_MekT0Erk;
       vector[D] EGF_train;
       vector[D] IGF_train;
    }
    transformed parameters {
      vector[D] SOS_loc;
      vector[D] Ras_loc;
      vector[D] AKT_loc;
      vector[D] Raf_loc;
      vector[D] Mek_loc;
      vector[D] Erk_loc;
      for (i in 1:D){
        SOS_loc[i] = 100 / (1 + exp(-beta0_EGFIGFToSOS - EGF_train[i] * beta_EGFToSOS - IGF_train[i] * beta_IGFToSOS));
        Ras_loc[i] = 100 / (1 + exp(-beta0_SOSToRas -SOS_train[i] * beta_SOSToRas));
        AKT_loc[i] = 100 / (1 + exp(-beta0_AKT - EGF_train[i] * beta_EGFToAKT - IGF_train[i] * beta_IGFToAKT - Ras_train[i] * beta_RasToAKT));
        Raf_loc[i] = 100 / (1 + exp(-beta0_RasAKTToRaf - Ras_train[i] * beta_RasToRaf - AKT_train[i] * beta_AKTToRaf));
        Mek_loc[i] = 100 / (1 + exp(-beta0_RafToMek - Raf_train[i] * beta_RafToMek));
        Erk_loc[i] = 100 / (1 + exp(-beta0_MekT0Erk - Mek_train[i] * beta_MekT0Erk));
      }
    }
    model {
        beta0_EGFIGFToSOS  ~ normal(0, 10); 
        beta_EGFToSOS  ~ normal(0, 10);
        beta_IGFToSOS  ~ normal(0, 10);
        mu_EGF ~ normal(37, 3);
        sigma_EGF ~ normal(1,1);
        mu_IGF ~ normal(5, 1);
        sigma_IGF ~ normal(1,1);
        beta_SOSToRas ~ normal(0, 10);
        beta0_AKT ~ normal(0,10);
        beta_EGFToAKT ~ normal(0,10);
        beta_IGFToAKT ~ normal(0,10);
        beta_RasToAKT ~ normal(0,10);
        beta0_RasAKTToRaf ~ normal(0,10);
        beta_RasToRaf ~ normal(0,10);
        beta_AKTToRaf ~ normal(0,10);
        beta0_RafToMek ~ normal(0,10);
        beta_RafToMek ~ normal(0,10);
        beta0_MekT0Erk ~ normal(0,10);
        beta_MekT0Erk ~ normal(0,10);
        EGF_train ~ normal(mu_EGF, sigma_EGF);
        IGF_train ~ normal(mu_IGF, sigma_IGF);
        SOS_train ~ normal(SOS_loc, 5.4);      // likelihood
        Ras_train ~ normal(Ras_loc, 5.3); //ras_loc = 47
        AKT_train ~ normal(AKT_loc,5.1);
        Raf_train ~ normal(Raf_loc,5.3);
        Mek_train ~ normal(Mek_loc,4.7);
        Erk_train ~ normal(Erk_loc,3.2);
    }
"
```

```{r, message=FALSE, warning=FALSE}
mod <- rstan::stan_model(model_code = model_str_IGF)
```

```{r, echo = FALSE}
#If you get this error (Cluster setup failed. 2 of 2 workers failed to connect.) run these lines:
if (Sys.getenv("RSTUDIO") == "1" && !nzchar(Sys.getenv("RSTUDIO_TERM")) &&
    Sys.info()["sysname"] == "Darwin") {
  parallel:::setDefaultClusterOptions(setup_strategy = "sequential")
}
observational_data <- read.csv("/Users/sarataheri/GitHub/ode2scm/data/observationalD500_igf.csv")
intervention_data <- read.csv("/Users/sarataheri/GitHub/ode2scm/data/interventionD500_igf_SOS70.csv")

D = 100
data_list <- list(D=D
                  ,SOS_train = observational_data$SOS[1:D]
                  ,AKT_train = observational_data$AKT[1:D]
                  ,Raf_train = observational_data$Raf[1:D]
                  ,Mek_train = observational_data$Mek[1:D]
                  ,Erk_train = observational_data$Erk[1:D]
                  ,Ras_train = observational_data$Ras[1:D]
                  )
```

```{r}
hmc_fit <- rstan::sampling(mod, data=data_list, chains = 2, iter = 3000, warmup = 1500, seed = 1#, control = list(max_treedepth = 15)
                           ) #seed 1
```

```{r}
stan_trace(pars = "mu_EGF", hmc_fit)
stan_trace(pars = "sigma_EGF", hmc_fit)
stan_trace(pars = "mu_IGF", hmc_fit)
stan_trace(pars = "sigma_IGF", hmc_fit)
stan_trace(pars = "beta0_EGFIGFToSOS", hmc_fit)
stan_trace(pars = "beta_EGFToSOS", hmc_fit)
stan_trace(pars = "beta_IGFToSOS", hmc_fit)
stan_trace(pars = "beta0_SOSToRas", hmc_fit)
stan_trace(pars = "beta_SOSToRas", hmc_fit)
stan_trace(pars = "beta0_AKT", hmc_fit)
stan_trace(pars = "beta0_RasAKTToRaf", hmc_fit)
stan_trace(pars = "beta_RasToRaf", hmc_fit)
stan_trace(pars = "beta_AKTToRaf", hmc_fit)
stan_trace(pars = "beta0_RafToMek", hmc_fit)
stan_trace(pars = "beta_RafToMek", hmc_fit)
stan_trace(pars = "beta0_MekT0Erk", hmc_fit)
stan_trace(pars = "beta_MekT0Erk", hmc_fit)
```

Now let's extract the samples:

```{r}
# everything one dimension
samples <- rstan::extract(hmc_fit, c("mu_EGF", "sigma_EGF"
                                     ,"mu_IGF", "sigma_IGF"
                                     ,"beta0_EGFIGFToSOS","beta_EGFToSOS", "beta_IGFToSOS"
                                     ,"beta0_SOSToRas","beta_SOSToRas"
                                     ,"beta0_AKT", "beta_EGFToAKT", "beta_IGFToAKT", "beta_RasToAKT"
                                     ,"beta0_RasAKTToRaf", "beta_RasToRaf", "beta_AKTToRaf"
                                     ,"beta0_RafToMek", "beta_RafToMek"
                                     ,"beta0_MekT0Erk", "beta_MekT0Erk"
                                     )
                          )
# mean(samples$mu_EGF)
# mean(samples$sigma_EGF)
# mean(samples$mu_IGF)
# mean(samples$sigma_IGF)
# mean(samples$beta0_SOSToRas)
# mean(samples$beta_SOSToRas)
# mean(samples$beta0_AKT)
# mean(samples$beta0_RasAKTToRaf)
# mean(samples$beta_RasToRaf)
# mean(samples$beta_AKTToRaf)
# mean(samples$beta0_RafToMek)
# mean(samples$beta_RafToMek)
# mean(samples$beta0_MekT0Erk)
# mean(samples$beta_MekT0Erk)
```

# Consistency plots

```{r}
num_samples = 1000
model <- function(mu_IGF, sigma_IGF, mu_EGF, sigma_EGF
                            ,beta0_EGFIGFToSOS, beta_EGFToSOS, beta_IGFToSOS
                            ,beta0_SOSToRas, beta_SOSToRas
                            ,beta0_AKT,beta_EGFToAKT, beta_IGFToAKT, beta_RasToAKT
                            ,beta0_RasAKTToRaf, beta_RasToRaf, beta_AKTToRaf
                            ,beta0_RafToMek, beta_RafToMek
                            ,beta0_MekT0Erk, beta_MekT0Erk
                            ) {
  EGF = rnorm(mu_EGF, sigma_EGF)
  IGF = rnorm(mu_IGF, sigma_IGF)
  SOS = 100 / (1 + exp(-beta0_EGFIGFToSOS - EGF * beta_EGFToSOS - IGF * beta_IGFToSOS)) + rnorm(num_samples,0,5.5)
  Ras = 100 / (1 + exp(-beta0_SOSToRas - SOS * beta_SOSToRas)) + rnorm(num_samples,0,5.5)
  AKT = 100 / (1 + exp(-beta0_AKT - EGF * beta_EGFToAKT - IGF * beta_IGFToAKT - Ras * beta_RasToAKT)) + rnorm(n = num_samples,0,5.2)
  Raf = 100 / (1 + exp(-beta0_RasAKTToRaf - Ras * beta_RasToRaf - AKT * beta_AKTToRaf)) + rnorm(n = num_samples,0,5.4)
  Mek = 100 / (1 + exp(-beta0_RafToMek - Raf * beta_RafToMek)) + rnorm(n = num_samples,0,4.9)
  Erk = 100 / (1 + exp(-beta0_MekT0Erk - Mek * beta_MekT0Erk)) + rnorm(n = num_samples,0,3.2)
  return(Erk)
}
mutilated_model <- function(mu_IGF, sigma_IGF, mu_EGF, sigma_EGF
                            ,beta0_EGFIGFToSOS, beta_EGFToSOS, beta_IGFToSOS
                            ,beta0_SOSToRas, beta_SOSToRas
                            ,beta0_AKT,beta_EGFToAKT, beta_IGFToAKT, beta_RasToAKT
                            ,beta0_RasAKTToRaf, beta_RasToRaf, beta_AKTToRaf
                            ,beta0_RafToMek, beta_RafToMek
                            ,beta0_MekT0Erk, beta_MekT0Erk
                            ,sos
                            ) {
  EGF = rnorm(mu_EGF, sigma_EGF)
  IGF = rnorm(mu_IGF, sigma_IGF)
  SOS = rep(sos, num_samples)
  Ras = 100 / (1 + exp(-beta0_SOSToRas - SOS * beta_SOSToRas)) + rnorm(num_samples,0,5.5)
  AKT = 100 / (1 + exp(-beta0_AKT - EGF * beta_EGFToAKT - IGF * beta_IGFToAKT - Ras * beta_RasToAKT)) + rnorm(n = num_samples,0,5.2)
  Raf = 100 / (1 + exp(-beta0_RasAKTToRaf - Ras * beta_RasToRaf - AKT * beta_AKTToRaf)) + rnorm(n = num_samples,0,5.4)
  Mek = 100 / (1 + exp(-beta0_RafToMek - Raf * beta_RafToMek)) + rnorm(n = num_samples,0,4.9)
  Erk = 100 / (1 + exp(-beta0_MekT0Erk - Mek * beta_MekT0Erk)) + rnorm(n = num_samples,0,3.2)
  return(Erk)
}
```


```{r}
# indexes = sample(length(samples$mu_EGF), 50, replace = FALSE)
# y_grey = list()
# #y_blue = list()
# #y_green = list()
# for (i in 1:length(indexes)) {
#   j = indexes[i]
#   #print(samples$beta_Ras[j])
#   y_grey[[i]] = mutilated_model(mu_IGF = samples$mu_IGF[j],
#                                 sigma_IGF = samples$sigma_IGF[j],
#                                 mu_EGF = samples$mu_EGF[j],
#                                 sigma_EGF = samples$sigma_EGF[j],
#                                 beta0_EGFIGFToSOS = samples$beta0_EGFIGFToSOS[j],
#                                 beta_EGFToSOS = samples$beta_EGFToSOS[j],
#                                 beta_IGFToSOS = samples$beta_IGFToSOS[j],
#                                 beta0_SOSToRas = samples$beta0_SOSToRas[j],
#                                 beta_SOSToRas = samples$beta_SOSToRas[j],
#                                 beta0_AKT = samples$beta0_AKT[j],
#                                 beta_EGFToAKT = samples$beta_EGFToAKT[j],
#                                 beta_IGFToAKT = samples$beta_IGFToAKT[j],
#                                 beta_RasToAKT = samples$beta_RasToAKT[j],
#                                 beta0_RasAKTToRaf = samples$beta0_RasAKTToRaf[j],
#                                 beta_RasToRaf = samples$beta_RasToRaf[j],
#                                 beta_AKTToRaf = samples$beta_AKTToRaf[j],
#                                 beta0_RafToMek = samples$beta0_RafToMek[j],
#                                 beta_RafToMek = samples$beta_RafToMek[j],
#                                 beta0_MekT0Erk = samples$beta0_MekT0Erk[j],
#                                 beta_MekT0Erk = samples$beta_MekT0Erk[j],
#                                 sos = 70
#                                 )
#   
# }
```

```{r}

y_grey_mean <-  mutilated_model(mu_IGF = mean(samples$mu_IGF),
                                sigma_IGF = mean(samples$sigma_IGF),
                                mu_EGF = mean(samples$mu_EGF),
                                sigma_EGF = mean(samples$sigma_EGF),
                                beta0_EGFIGFToSOS = mean(samples$beta0_EGFIGFToSOS),
                                beta_EGFToSOS = mean(samples$beta_EGFToSOS),
                                beta_IGFToSOS = mean(samples$beta_IGFToSOS),
                                beta0_SOSToRas = mean(samples$beta0_SOSToRas),
                                beta_SOSToRas = mean(samples$beta_SOSToRas),
                                beta0_AKT = mean(samples$beta0_AKT),
                                beta_EGFToAKT = mean(samples$beta_EGFToAKT),
                                beta_IGFToAKT = mean(samples$beta_IGFToAKT),
                                beta_RasToAKT = mean(samples$beta_RasToAKT),
                                beta0_RasAKTToRaf = mean(samples$beta0_RasAKTToRaf),
                                beta_RasToRaf = mean(samples$beta_RasToRaf),
                                beta_AKTToRaf = mean(samples$beta_AKTToRaf),
                                beta0_RafToMek = mean(samples$beta0_RafToMek),
                                beta_RafToMek = mean(samples$beta_RafToMek),
                                beta0_MekT0Erk = mean(samples$beta0_MekT0Erk),
                                beta_MekT0Erk = mean(samples$beta_MekT0Erk),
                                sos = 70
                                )
y_grey_mean2 <-  model(mu_IGF = mean(samples$mu_IGF),
                                sigma_IGF = mean(samples$sigma_IGF),
                                mu_EGF = mean(samples$mu_EGF),
                                sigma_EGF = mean(samples$sigma_EGF),
                                beta0_EGFIGFToSOS = mean(samples$beta0_EGFIGFToSOS),
                                beta_EGFToSOS = mean(samples$beta_EGFToSOS),
                                beta_IGFToSOS = mean(samples$beta_IGFToSOS),
                                beta0_SOSToRas = mean(samples$beta0_SOSToRas),
                                beta_SOSToRas = mean(samples$beta_SOSToRas),
                                beta0_AKT = mean(samples$beta0_AKT),
                                beta_EGFToAKT = mean(samples$beta_EGFToAKT),
                                beta_IGFToAKT = mean(samples$beta_IGFToAKT),
                                beta_RasToAKT = mean(samples$beta_RasToAKT),
                                beta0_RasAKTToRaf = mean(samples$beta0_RasAKTToRaf),
                                beta_RasToRaf = mean(samples$beta_RasToRaf),
                                beta_AKTToRaf = mean(samples$beta_AKTToRaf),
                                beta0_RafToMek = mean(samples$beta0_RafToMek),
                                beta_RafToMek = mean(samples$beta_RafToMek),
                                beta0_MekT0Erk = mean(samples$beta0_MekT0Erk),
                                beta_MekT0Erk = mean(samples$beta_MekT0Erk)
                                )

df_CE_on_Erk <- data.frame(type = c(rep("True(SDE)",500),rep("LVM",500)),
                           value = c((intervention_data$Erk[1:500]), (y_grey_mean[1:500]))) #pay attention to length interventional data
pp <- df_CE_on_Erk %>% ggplot( aes(x=value, fill=type, color = type)) +
    geom_histogram(color="#e9ecef", alpha=0.6, position = 'identity', bins = 18) + 
  theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.line = element_line(colour = "black"),
          legend.title = element_text(color = "black", size = 18, face = "bold"),
          legend.text = element_text(color = "black", size = 14),
          axis.text=element_text(size=14),
          axis.title=element_text(size=18,face="bold"),
          legend.position = "top"
          ) +
    guides(fill=guide_legend(title="Samples of P(Erk | do(SOS = 70))")) +
    xlab("Samples")
pp
#ggsave("distOverErknonInformative.pdf", plot = pp, width = 7, height = 7, dpi = 300, units = "in")
```
